### ISSUE TITLE
Implement events command

### ISSUE THREAD

**Issue by harlem88** [joshuachp/dockrs#22]
Get real time events from the server

```
dockrs events [OPTIONS]
```
Also try writing a function that returns a channel of `DockerEvent`.

```rust
struct DockerEvent{
 object_type: ObjectType,
 event: Event,
 action: String
}
....

fn docker_events() -> Receiver<DockerEvent>{}

```

### Containers
Docker containers report the following events:
- attach
- commit
- copy
- create
- destroy
- detach
- die
- exec_create
- exec_detach
- exec_die
- exec_start
- export
- health_status
- kill
- oom
- pause
- rename
- resize
- restart
- start
- stop
- top
- unpause
- update

### Images
Docker images report the following events:
- delete
- import
- load
- pull
- push
- save
- tag
- untag

### Volumes
Docker volumes report the following events:
- create
- destroy
- mount
- unmount

### Networks
Docker networks report the following events:
- create
- connect
- destroy
- disconnect
- remove

### Daemons
Docker daemons report the following events:
- reload

 [https://docs.docker.com/engine/reference/commandline/events/](https://docs.docker.com/engine/reference/commandline/events/)

**Comment by joshuachp** [comment]
There is no need to return a channel since the api already returns an async stream of events
